### ISSUE TITLE
Background for raster sources

### ISSUE THREAD

**Issue by otsaloma** [rinigus/mapbox-gl-qml#27] opened 2018-01-07 20:50 UTC
With raster sources, I'm seeing the Sailfish ambience background where no tiles have yet been loaded. It's easiest to test by setting a bogus tile URL, where all tile downloads fail. A good default would be "#e6e6e6", which works well for most light background maps.

**Comment by rinigus** [comment] 2018-01-08 11:10
I haven't tested it, but I think you can add a background layer before raster layer. For WhoGo Maps, it means adding one more layer in front ofhttps://github.com/otsaloma/whogo-maps/blob/master/poor/application.py#L81 . Something like

```json
[
       { "id": "background",
         "type": "background",
         "paint": { "background-color": "#e6e6e6" }
        },
        {
            "id": "raster",
            "type": "raster",
            "source": "raster",
            "layout": {
                "visibility": "visible"
            },
            "paint": {
                "raster-opacity": 1
            }
        }
    ]
```

should solve the issue. As a bonus, the color can be matched to the default for current raster source.

**Comment by otsaloma** [comment] 2018-01-08 20:40
Yeah, that works. I tried it already yesterday, but must've gotten something wrong. This works fine for me, I'll leave it up to you whether you want to include a background it into MapboxMap – it might be good to have, but not a big deal.

**Comment by rinigus** [comment] 2018-01-08 21:09
I think then I'll close it. It seems to me that all styles are expected to have background and its by design to have the widget transparent otherwise. At least all vector tiles do have background element in them.

**Closed by rinigus** 2018-01-08 21:09 UTC
